default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_general_ci
  username: root
  password: root

development:
  <<: *default
  database: business_worty
  username: root
  password: root

test:
  <<: *default
  database: business_worty_test
  username: root
  password: root

production:
  <<: *default
  database: business_worty_production
  username: root
  password: root

staging:
   <<: *default
   database: business_worty_staging